#' Convert the sims output from the saom_simulate function to a dataframe object.
#'
#' @param sims list output from the saom_simulate function or from ans$sims where ans was generated by RSiena::siena07()
#'
#' @examples
#' M1sims5df <- sims_to_df(M1sims5)
#'
#' @export
sims_to_df <- function(sims){
  N <- length(sims)
  waves <- length(sims[[1]][[1]][[1]])
  #count.rows <- rep(0, N)
  #lapply(sims, FUN = function(x) nrow(x[[1]][[1]][[2]]))
  simsdf <- NULL
  for (i in 1:N){
    for(j in 1:waves){
      dat <- as.data.frame(sims[[i]][[1]][[1]][[j]])
      names(dat) <- c("from", "to", "dep.var.id")
      ids <- unique(c(unique(dat$from), unique(dat$to)))
      nodes <- data.frame(id = ids)
      dat2 <- merge(dat, nodes, by.x = "from", by.y = "id", all = T)
      dat2$wave = j
      dat2$sim = i
      simsdf <- rbind(simsdf, dat2)
    }
  }
  return(simsdf)
}
